
tasks:
  - name: install
    command: |
      yarn install && yarn run build
      gp sync-done install-yarn
      yarn run start
  - name: storybook
    command: |
      gp sync-await install-yarn
      yarn storybook



vscode:
  extensions:
    - dsznajder.es7-react-js-snippets